### ISSUE TITLE
Icons lose the ability to be resized by bartender 4 when updated to 10.0-004 or 10.0-005

### ISSUE THREAD

**Issue by Zepherouss** [teelolws/SLMicroMenu#5]
![image](https://user-images.githubusercontent.com/19320080/200113923-22e63c7d-e3f1-4400-aa5b-83eb8ee0bd5d.png)
![image](https://user-images.githubusercontent.com/19320080/200113937-4d91c36b-d2cc-4262-8e70-b129bfa95f5f.png)
Was working fine on 10.0-003 but since updating to 10.0-004 it seems to be ignoring Bartenders resizing.

**Comment by teelolws** [comment]
Resize it with my addon instead. Go into Edit Mode. You should have the option to move and resize the menu bar and backpack bar now.

**Comment by Zepherouss** [comment]
Using your addon did allow me to resize via edit mode with the position and icon spacing is still controlled by bartender.
Would it be possible have a setting to allow it to just control the texture and allow sizing to be control by other addons?
Thanks for the fix in the meantime though.

**Comment by teelolws** [comment]
Looking into Bartenders code, it looks like they completely replace the Menu Bar with their own. And I'm doing the same thing. Its due to a problem with some code Blizzard has, that requires the original Menu Bar to always be at the bottom right of the screen, or it causes errors.

I'll look into it more tomorrow. I might just disable the duplication and resizing if I detect Bartender4 installed.
