### ISSUE TITLE
Collapse bags button 

### ISSUE THREAD

**Issue by Talimar** [teelolws/SLMicroMenu#8]
Hey. With this installed together with Dominos, there is a collapse bag bar button being shown that is otherwise hidden. It also doesn't do anything.
Is it possible to remove it?
![Wow_iHncV5TFCH](https://user-images.githubusercontent.com/21211868/202737547-cffbeb6c-269d-4df7-a0bc-ba99420f2d0d.png)

**Comment by Memathaes** [comment]
It appears that with ElvUI enabled, the triangle also shows up. There's other issues with ElvUI too that are not the fault of this addon I don't think (scaling/positioning of the icons is off but that's caused by ElvUI's built-in skin on the micro bar I believe, and you can't disable it without disabling the entirety of their action bar system), but the triangle I assume is on your end based on the other user's issue and the code that fixed it.
![image](https://user-images.githubusercontent.com/9143424/202971416-914153ec-741a-45ea-bc6a-f18c9aaaa867.png)
(Triangle is showing over the rightmost micro bar icon, since I realized it's kind of not immediately visible with the color similarity)

**Comment by teelolws** [comment]
After the next addon patch, go into your interface options and uncheck this:

![image](https://user-images.githubusercontent.com/49792789/202974079-a19e8c69-0930-4e6d-9637-a4f5df1e8e41.png)
